name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run React Testing Library Tests
      run: npm test

    - name: Start Server
      run: npm start &
      env:
        CI: true

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6

